### ISSUE TITLE
Create Directory Structure & install dependencies 

### ISSUE THREAD

**Issue by njsfield** [foundersandcoders/Live-Peers#27]
- [x] Create directory structure
- [x] Install dependencies

**Comment by jsms90** [comment]
Dependencies:
+ inert, vision
+ hapi, hapi-auth-cookie, hapi-error
+ handlebars - handling views server-side, since we have so much dynamic content
+ socket.io - because we're using web sockets instead of polling
+ env2 - for ease of heroku hosting

Dev dependencies:
+ nodemon - so we don't have to constantly restart the server manually
+ eslint, eslint-config-semistandard, eslint-config-standard, eslint-plugin-promise, eslint-plugin-standard - linting tools
+ tape, tap-spec, istanbul, codecov - code coverage tools
